CREATE TABLE `POSTS`
(
    `PAGE_ID`        CHAR(12)     NOT NULL COMMENT '아이디',
    `POST_TITLE`     VARCHAR(35)  NOT NULL COMMENT '게시글 제목',
    `POST_CONTENT`   VARCHAR(999) NOT NULL COMMENT '게시글 내용',
    `PAGE_NICKNAME`  CHAR(8)      NOT NULL COMMENT '닉네임',
    `POST_CREATEDAT` TIMESTAMP    NOT NULL COMMENT '작성시간',
    PRIMARY KEY (`PAGE_ID`)
) COMMENT = '게시물';

CREATE TABLE `COMMENTS`
(
    `PAGE_ID`        CHAR(12)     NOT NULL COMMENT '아이디',
    `COMMENT_CONTENT`   VARCHAR(999) NOT NULL COMMENT '댓글 내용',
    `PAGE_NICKNAME`  CHAR(8)      NOT NULL COMMENT '닉네임',
    
    PRIMARY KEY (`PAGE_ID`)
) COMMENT = '게시물';